name: Lint を実行

on:
  pull_request:
    branches:
      - main
      - canary
    types:
      - opened
      - synchronize
    paths:
      - "src/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install modules
        run: pnpm install

      - name: Lint
        run: pnpm lint
