name: Lint を実行

on:
  pull_request:
    branches:
      - main
      - canary
    types:
      - opened
      - synchronize
    paths:
      - "src/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install safe-chain
        run: curl -fsSL https://raw.githubusercontent.com/AikidoSec/safe-chain/main/install-scripts/install-safe-chain.sh | sh -s -- --ci
        env:
          SAFE_CHAIN_VERSION: "1.2.1"

      - name: Install modules
        run: pnpm install

      - name: Lint
        run: pnpm lint
